### ISSUE TITLE
Code style

### ISSUE THREAD

**Issue by tshemsedinov** [mezgoodle/Caesar-and-Vigenere-ciphers#10]
- [x] Long lines (80 is maximum)
- [x] Identifier naming, use camel case
- [x] Use block `{}` for if statement when it is not single-line
- [x] If first statement of if operator have block `{}` else statement also should have block `{}` braces
- [x] Defile variables separately, not like this: `let result = '', keyIndex = 0;`
- [x] Use operator-like form `typeof amount`, not function-like `typeof(amount)`
- [x] There are good cases for partial application

**Comment by mezgoodle** [comment]
Problems were fixed
